import AuthProvider from '@/providers/AuthProvider'
import './globals.css'
import { Poppins } from 'next/font/google'
import Header from '@/components/Header'

const inter = Poppins({ subsets: ['latin'], weight: "500" })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <AuthProvider>
      <html  lang="en" data-theme="coffee">
        <body className={`${inter.className}`}>
          <Header/>
          {children}
        </body>
      </html>
    </AuthProvider>
  )
}
